apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lms-role
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "molt-lms.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
        - ""
    resources:
      - endpoints
    verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lms-rolebinding
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "molt-lms.labels" . | nindent 4 }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lms-role 
subjects:
- kind: ServiceAccount
  name: {{ include "molt-lms.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
