{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "molt-lms.fullname" . }}
  namespace : {{ .Release.namespace | quote }}
  labels:
    {{- include "molt-lms.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml .Values.serviceMonitor.annotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "molt-lms.selectorLabels" . | nindent 6 }}
    {{- with .Values.lms.service.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.orchestrator.service.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.labels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  namespaceSelector:
  {{- if .Values.serviceMonitor.namespaced }}
    matchNames:
      - {{ .Release.Namespace }}
  {{- else }}
    any: true
  {{- end }}
  endpoints:
  - port: metrics
    path: /vars
    {{- if .Values.serviceMonitor.interval }}
    interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- end }}
{{- end }}
