apiVersion: v1
kind: Service
metadata:
  name: {{ include "molt-lms.fullname" . }}
  namespace : {{ .Release.namespace | quote }}
  labels:
    {{- include "molt-lms.labels" . | nindent 4 }}
  {{- with .Values.lms.service.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.lms.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.lms.service.type }}
  ports:
    - port: {{ .Values.lms.service.port }}
      name: lms
      protocol: TCP
    - port: {{ .Values.lms.service.metricsPort }}
      name: metrics
      protocol: TCP
  selector:
    {{- include "molt-lms.selectorLabels" . | nindent 4 }}
  {{- with .Values.lms.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
